# Generated by Django 4.0 on 2021-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
